parameters:
#    salon_solution_admin.example.class: SalonSolution\AdminBundle\Example

services:
#    salon_solution_admin.example:
#        class: %salon_solution_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
