parameters:
#    salon_solution_employee.example.class: SalonSolution\EmployeeBundle\Example

services:
#    salon_solution_employee.example:
#        class: %salon_solution_employee.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
