parameters:
#    salon_solution_salon.example.class: SalonSolution\SalonBundle\Example

services:
#    salon_solution_salon.example:
#        class: %salon_solution_salon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
